### ISSUE TITLE
Auto-build docker images as part of the CI

### ISSUE THREAD

**Issue by nmiculinic** [calendso/docker#20]
The docker images should be built as part of the (release) CI pipeline and pushed to registry; (you can use GitHub registry fwiw)

## Describe the solution you'd like

Use of many pre-packages Github actions for building docker images & pushing them to registry
It's relatively easy to do, some googling and some copy-paste

**Comment by PeerRich** [comment]
@emrysal 🙏

**Comment by krumware** [comment]
quick note:
based on some of the other issues, some additions may need to be made to the dockerfile to allow ENV variables to be passed in at docker build time so that `yarn build` is able to read those buildtime variables.
ref comments in: #11

**Comment by nmiculinic** [comment]
ok, but why? 

I mean docker container shouldn't be that opinionated (my idea is deploying it to k8s via helm chart for something). You can always pass in envfile via:

```
docker run --env-file
```

**Comment by nmiculinic** [comment]
This is classic FE + backend server + PostgreSQL app; 

those configurations should not be hard-coded in the image but passed in during the run time. Otherwise, you're making the operational aspect hard if I have to rebuild the image for a new environment, thus defeating the purpose of the image.

**Comment by krumware** [comment]
I agree with you. Currently it does not appear the env vars are working properly at runtime via docker. Also, many frontends bake variables into the container at build time when compiling static content (unfortunately) and I'm hoping that isn't happening here, but it appears to be.

My preference would be that all the variables work at runtime. In the case where the production build bakes static content, there at least needs to be a way to expose those variables at build time. Just wanted to make the note.

**Comment by krumware** [comment]
notes here:
There was a conscious decision by the cal team to move away from client-side runtime variables: https://github.com/calendso/calendso/pull/651#pullrequestreview-755077204
But I haven't verified what variables are compiled into the client static files.

I couldn't find reference to use of serverruntimeconfig variables or getConfig() in calendso/calendso, after referencing the next.js docs https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration

regardless, still having trouble with the build due to the use of prisma+next, which seems to require a database connection at build time. this is easy enough to resolve with github actions but it mean further build-time dependencies for custom ci/cd

**Comment by emrysal** [comment]
Hi @krumware - I'll have a look at what is required to remove the db connection requirement at build time.

Re.
> Also, many frontends bake variables into the container at build time when compiling static content (unfortunately)

I assume what is intended here is during build time of the container itself, because in terms of during a nextJS production build I'd strongly argue for a position to prefer env variable configuration to be done as a static part of the build or keep it in the BE entirely. In this specific instance - calendso/calendso#651 we had a runtime configuration for the client side BASE_URL (as we no longer wanted to depend on window.location to determine this). 

This position is recommended by the NextJS team as well:

> Generally you'll want to use build-time environment variables to provide your configuration. The reason for this is that runtime configuration adds rendering / initialization overhead and is incompatible with Automatic Static Optimization.

**Comment by krumware** [comment]
Thanks for the extra context! I understand their approach for the static build, especially in cases of precache and file hash consistency across load balanced file servers. (interested in calendlo's current status for load balanced support on the API side, tackle later). Another approach I have seen here in the k8s space is to use an initialization sidecar to re-perform the static build to a shared volume.

Part of my goal would be to provide an interface for development and experiment convenience, which I think we've shown can be accomplished by leveraging `yarn dev` and some other runtime config which I can document and specify. 

(obviously there are several opinionated options, and still active discussion on some threads over on the nextjs side)

---

Back on topic, client-side variables can be exposed in the dockerfile for build time secrets injection prior to the static build steps.

Do you know if the server vars like process.env.database_url are also replaced in next production build, or if those are still supported at runtime?

**Comment by krumware** [comment]
Closing, this is now building and pushing automatically
